---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: richxsl/rhel7:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    pre_build_image: true
provisioner:
  name: ansible
verifier:
 name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  name: default
  test_sequence:
  - dependency
  - lint
  - cleanup
  - destroy
  - create
  - prepare
  - converge
  - idempotence
  - verify
  - cleanup
  - destroy

